### ISSUE TITLE
Deprecated selector in `ironman-syntax/index.less`

### ISSUE THREAD

**Issue by matthewlgm** [lode/ironman-syntax#1]
In `ironman-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `.comment` => `.syntax--comment`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.constant` => `.syntax--constant`

* `.variable` => `.syntax--variable`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.numeric` => `.syntax--string.syntax--numeric`

* `.support.class` => `.syntax--support.syntax--class`

* `.support.other.namespace` => `.syntax--support.syntax--other.syntax--namespace`

* `.support.constant` => `.syntax--support.syntax--constant`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.function.any-method` => `.syntax--support.syntax--function.syntax--any-method`

* `.entity` => `.syntax--entity`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.tag.sgml,
.tag.structure,
.tag.block` => `.syntax--tag.syntax--sgml,
.syntax--tag.syntax--structure,
.syntax--tag.syntax--block`

* `.tag.sgml .other.attribute-name,
.tag.structure .other.attribute-name,
.tag.block .other.attribute-name` => `.syntax--tag.syntax--sgml .syntax--other.syntax--attribute-name,
.syntax--tag.syntax--structure .syntax--other.syntax--attribute-name,
.syntax--tag.syntax--block .syntax--other.syntax--attribute-name`

* `.tag.inline,
.tag.style` => `.syntax--tag.syntax--inline,
.syntax--tag.syntax--style`

* `.tag.inline .punctuation,
.tag.style .punctuation` => `.syntax--tag.syntax--inline .syntax--punctuation,
.syntax--tag.syntax--style .syntax--punctuation`

* `.tag.doctype` => `.syntax--tag.syntax--doctype`

* `.source.css .constant` => `.syntax--source.syntax--css .syntax--constant`

* `.source.css .support.type` => `.syntax--source.syntax--css .syntax--support.syntax--type`

* `.source.css .support.property-value` => `.syntax--source.syntax--css .syntax--support.syntax--property-value`

* `.source.css .support.color` => `.syntax--source.syntax--css .syntax--support.syntax--color`

* `.source.css .entity:not(.html)` => `.syntax--source.syntax--css .syntax--entity:not(.html)`

* `.source.css .entity:not(.html).pseudo-class` => `.syntax--source.syntax--css .syntax--entity:not(.html).syntax--pseudo-class`

* `.source.js .entity.function` => `.syntax--source.syntax--js .syntax--entity.syntax--function`

* `.source.sql .entity.name` => `.syntax--source.syntax--sql .syntax--entity.syntax--name`

* `.template` => `.syntax--template`

* `.template .entity.name.tag` => `.syntax--template .syntax--entity.syntax--name.syntax--tag`

* `.template .entity.name.tag .punctuation` => `.syntax--template .syntax--entity.syntax--name.syntax--tag .syntax--punctuation`

* `.template .entity.name.tag .entity.function` => `.syntax--template .syntax--entity.syntax--name.syntax--tag .syntax--entity.syntax--function`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `.source.gfm .heading` => `.syntax--source.syntax--gfm .syntax--heading`

* `.source.gfm .heading .marker` => `.syntax--source.syntax--gfm .syntax--heading .syntax--marker`

* `.source.gfm .list` => `.syntax--source.syntax--gfm .syntax--list`

* `.source.gfm .link` => `.syntax--source.syntax--gfm .syntax--link`

* `.source.gfm .link .entity` => `.syntax--source.syntax--gfm .syntax--link .syntax--entity`

* `.source.gfm .hr` => `.syntax--source.syntax--gfm .syntax--hr`

* `.source.gfm .emoji` => `.syntax--source.syntax--gfm .syntax--emoji`

* `.source.gfm .raw.inline` => `.syntax--source.syntax--gfm .syntax--raw.syntax--inline`

* `.markup.link:hover` => `.syntax--markup.syntax--link:hover`

* `.line .gfm.code::after` => `.line .syntax--gfm.syntax--code::after`

* `.line .gfm.hr::after` => `.line .syntax--gfm.syntax--hr::after`

* `atom-text-editor::shadow .markup.raw.gfm` => `atom-text-editor.editor .syntax--markup.syntax--raw.syntax--gfm`

* `atom-text-editor[mini] .scroll-view,
:host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lode** [comment]
Thanks for the push. I fixed this before but forgot the publishing using apm. That is done now, seems to work correctly for me, can you confirm it is fixed for you?

**Comment by matthewlgm** [comment]
It's has been fixed. I just confirmed. Thanks Iode.

**Comment by lode** [comment]
Nice, thanks again for noticing!
